<a href="https://colab.research.google.com/github/AlinaSharonova/AlinaSharonova/blob/master/27septemberNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Basic Number 11
Напишите программу NumPy для создания поэлементного сравнения (равного, равного в пределах допуска) двух заданных массивов.  

In [8]:
import numpy as np
x = np.array([2, 22, 33, 44, 100, -1, -10])
y = np.array([-52, 7, 8, 0, 150, -13, 121.0])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.greater(x, y))
print("Comparison - equal within a tolerance:")
print(np.greater_equal(x, y))


Original numbers:
[  2  22  33  44 100  -1 -10]
[-52.   7.   8.   0. 150. -13. 121.]
Comparison - equal:
[ True  True  True  True False  True False]
Comparison - equal within a tolerance:
[ True  True  True  True False  True False]


Numpy Basic Number 21
Напишите программу NumPy для создания вектора длиной 10 со значениями, равномерно распределенными между 5 и 50.  


In [4]:
import numpy as np
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)


Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


Numpy Basic Number 31
Напишите программу NumPy для создания массива 3x3x3, заполненного произвольными значениями.

In [11]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x)


[[[9.07192279e-02 8.71460468e-01 1.11655019e-01]
  [2.28391195e-01 6.31566207e-01 6.66376744e-01]
  [3.85832969e-01 6.96638372e-01 3.39567814e-04]]

 [[6.49559851e-01 5.55322757e-01 5.79063581e-01]
  [4.97686797e-02 4.38069728e-02 9.14087364e-01]
  [7.10420195e-01 7.68259900e-01 9.71618638e-03]]

 [[9.87199810e-01 6.50645604e-01 6.96270395e-01]
  [3.77171096e-01 7.68508454e-01 7.94471583e-01]
  [5.13573553e-02 5.49320937e-01 2.76330387e-01]]]


NumPy: упражнения с массивом

Number 11

Напишите программу NumPy для преобразования списка и кортежа в массивы.  
Список в массив:
[1 2 3 4 5 6 7 8]
Кортеж в массив:
[[8 4 6]
[1 2 3]]


In [14]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


NumPy: упражнения с массивом

Number 21

Напишите программу NumPy, чтобы найти набор исключений или двух массивов. Set exclusive-or вернет отсортированные, уникальные значения, которые находятся только в одном (а не в обоих) входных массивах.  
Array1: [0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Уникальные значения, которые есть только в одном (а не в обоих) входных массивах:
[0 20 30 50 60 70 80]


In [18]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 20 30 50 60 70 80]


NumPy: упражнения с массивом

Number 31

Напишите программу NumPy, чтобы получить значения и индексы элементов, которые больше 10 в данном массиве.  
Исходный массив:
[[0 10 20]
[20 30 40]]
Значения больше 10 = [20 20 30 40]
Их индексы (массив ([0, 1, 1, 1]), массив ([2, 0, 1, 2]))


In [19]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Линейная алгебра NumPy

Number 11

Напишите программу NumPy для вычисления определителя массива. 

In [21]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


NumPy: случайные упражнения

Number 11

Напишите программу NumPy для создания случайного вектора размером 15 и замените максимальное значение на -1.  


In [22]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.37414557 0.26061089 0.66824569 0.4343545  0.45826735 0.48986644
 0.5986174  0.40275369 0.29390684 0.6127944  0.0065124  0.18762822
 0.61216826 0.27338598 0.63256552]
Maximum value replaced by -1:
[ 0.37414557  0.26061089 -1.          0.4343545   0.45826735  0.48986644
  0.5986174   0.40275369  0.29390684  0.6127944   0.0065124   0.18762822
  0.61216826  0.27338598  0.63256552]


NumPy: математические упражнения

Number 11

Напишите программу NumPy, чтобы умножить матрицу 5x3 на матрицу 3x2 и создать реальный матричный продукт. 

In [23]:
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)


First array:
[[0.05960408 0.89470147 0.45062836]
 [0.57801333 0.65358626 0.74143712]
 [0.71185921 0.03026638 0.26905931]
 [0.95347824 0.34347507 0.14840681]
 [0.48519611 0.44231192 0.23123356]]
Second array:
[[0.08334428 0.50249967]
 [0.63008001 0.12431329]
 [0.23843446 0.51311267]]
Dot product of two arrays:
[[0.6761465  0.37239743]
 [0.6367699  0.75214174]
 [0.14255265 0.49952927]
 [0.33126904 0.59797043]
 [0.37426427 0.417445  ]]
