<a href="https://colab.research.google.com/github/AlinaSharonova/AlinaSharonova/blob/master/NumpyLecture3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
Транспонирование матрицы

In [ ]:
import numpy as np
a = np.array([[1, 3,-1], [5, 2,0], [0,5,1]],
float)
b=a.T
print("A:")
print(a)
print("\n a.T")
print(b)

A:
[[ 1.  3. -1.]
 [ 5.  2.  0.]
 [ 0.  5.  1.]]

 a.T
[[ 1.  5.  0.]
 [ 3.  2.  5.]
 [-1.  0.  1.]]


Cоединение матриц по горизонтали и по вертикали.

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8,
9]])
print("A:")
print(a)
print("B:")
print(b)
print("C:")
print(c)
print("np.hstack((a, b)):")
d=np.hstack((a, b))
print(d)
print("np.vstack((a, c)):")
e=np.vstack((a, c))
print(e)

A:
[[0 1]
 [2 3]]
B:
[[4 5 6]
 [7 8 9]]
C:
[[4 5]
 [6 7]
 [8 9]]
np.hstack((a, b)):
[[0 1 4 5 6]
 [2 3 7 8 9]]
np.vstack((a, c)):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [ ]:
import numpy as np
a = np.array([[4, 5, 6], [7, 8,
9]])
print("A:")
print(a)
print("Сумма всех элементов" ,"a.sum():")
b=a.sum()
print(b)
print("Сумма столбцов", "a.sum(axis=0):")
c=a.sum(axis=0)
print(c)
print("Сумма строк", "a.sum(axis=1):")
d=a.sum(axis=1)
print(d)

A:
[[4 5 6]
 [7 8 9]]
Сумма всех элементов a.sum():
39
Сумма столбцов a.sum(axis=0):
[11 13 15]
Сумма строк a.sum(axis=1):
[15 24]


Сумма диагональных элементов.

In [ ]:
import numpy as np
a = np.array([[0, 1], [2,
3]])
print("A:")
print(a)
print("np.trace(a):")
b=np.trace(a)
print(b)

A:
[[0 1]
 [2 3]]
np.trace(a):
3


Одиночное (cингулярное) разложение (аналог диагонализации не
квадратной матрицы)

In [ ]:
from calendar import c
import numpy as np
a = np.array([[1, 3,4], [5, 2, 3]],
float)
U, s, Vh = np.linalg.svd(a)
print("A:")
print(a)
print("\n U:")
print(U)
print("\n s:")
print(s)
print("\n Vh:")
print(Vh)

A:
[[1. 3. 4.]
 [5. 2. 3.]]

 U:
[[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]]

 s:
[7.46791327 2.86884495]

 Vh:
[[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]]


норма вектора или оператора.

In [ ]:
import numpy as np
a = np.array([1,2,5,7,9],
float)
b=np.linalg.norm(a)
print("A:")
print(a)
print("\n Norm(a):")
print(b)

A:
[1. 2. 5. 7. 9.]

 Norm(a):
12.649110640673518


"хорошее" решение

In [ ]:
import numpy as np
x = np.array([[-3, 4, 1], [4, 3, 1]])
y = np.array([10, 12])
I = np.eye(3)
lambd = 0.1
theta = np.linalg.inv(x.T @ x + lambd * I) @x.T@y
print(theta)

[0.68478852 2.80148778 0.81180812]


Математика многочленов

Передавая
список корней, можно получить коэффициенты уравнения:

In [ ]:
import numpy as np
a=np.poly([-1, 1, 1,
10])
print("A:")
print(a)

A:
[  1. -11.   9.  11. -10.]


передавая список коэффициентов, функция root вернет все корни многочлена:

In [ ]:
import numpy as np
a=np.roots([1, -11, 9, 11, -10])
print("A:")
print(a)

A:
[10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]


Решение линейной системы. 
Вариант 1

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
v = np.array([0, 1],
dtype=np.float64)
print("A:")
print(a)
print("\n V:")
print(v)
a1 = np.linalg.inv(a)
print("\n a^(-1):")
print(a1)
u=a1 @ v
print("\n U:")
print(u)

A:
[[0 1]
 [2 3]]

 V:
[0. 1.]

 a^(-1):
[[-1.5  0.5]
 [ 1.   0. ]]

 U:
[0.5 0. ]


Решение линейной системы. Вариант 2

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
v = np.array([0, 1],
dtype=np.float64)
print("A:")
print(a)
print("\n V:")
print(v)
u = np.linalg.solve(a, v)
print("\n U:")
print(u)

A:
[[0 1]
 [2 3]]

 V:
[0. 1.]

 U:
[0.5 0. ]


Проверка

In [ ]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
v = np.array([0, 1],
dtype=np.float64)
print("A:")
print(a)
print("\n V:")
print(v)
u = np.linalg.solve(a, v)
print("\n U:")
print(u)
print("a @ u - v :")
x=a @ u - v
print(x)

A:
[[0 1]
 [2 3]]

 V:
[0. 1.]

 U:
[0.5 0. ]
a @ u - v :
[0. 0.]


Функция diag от одномерного массива строит диагональную матрицу;
от квадратной матрицы — возвращает одномерный массив её диагональных
элементов.

In [ ]:
import numpy as np
a = np.array([[0, 1], [2,
3]])
print("A:")
print(a)
print("diag(a):")
L = np.diag(a)
print(L)
print("diag(L): ")
print(np.diag(L))

A:
[[0 1]
 [2 3]]
diag(a):
[0 3]
diag(L): 
[[0 0]
 [0 3]]


100 задач

In [8]:
#Импортировать NumPy под именем np
import numpy as np
#Напечатать версию и конфигурацию
print(np.__version__)
np.show_config()
#Создать вектор (одномерный массив) размера 10, заполненный нулями
Z = np.zeros(10)
print(Z)
#Создать вектор размера 10, заполненный единицами
Z = np.ones(10)
print(Z)
#Создать вектор размера 10, заполненный числом 2.5
Z = np.full(10, 2.5)
print(Z)
#Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1
Z = np.zeros(10)
Z[4] = 1
print(Z)
#Создать вектор со значениями от 10 до 49
Z = np.arange(10,50)
print(Z)
#Развернуть вектор (первый становится последним)
Z = np.arange(50)
Z = Z[::-1]
#Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
nz = np.nonzero([1,2,0,0,4,0])
print(nz)
#Создать 3x3 единичную матрицу
Z = np.eye(3)
print(Z)
#Создать массив 3x3x3 со случайными значениями
Z = np.random.random((3,3,3))
print(Z)
#Создать массив 10x10 со случайными значениями, найти минимум и максимум
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

#Создать случайный вектор размера 30 и найти среднее значение всех элементов
Z = np.random.random(30)
m = Z.mean()
print(m)
#Создать матрицу с 0 внутри, и 1 на границах
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
#Выяснить результат следующих выражений
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
#Создать 5x5 матрицу с 1,2,3,4 под диагональю
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)
#Создать 8x8 матрицу и заполнить её в шахматном порядке
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)
#Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))
#Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)
#Перемножить матрицы 5x3 и 3x2
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
#Создать 5x5 матрицу со значениями в строках от 0 до 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
#Есть генератор, сделать с его помощью массив
def generate():
  for x in range(10):
    yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)
#Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое
Z = np.linspace(0,1,12)[1:-1]
print(Z)
#Отсортировать вектор
Z = np.random.random(10)
Z.sort()
print(Z)
#Проверить, одинаковы ли 2 numpy массива
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
# Сделать массив неизменяемым
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0]=1
#Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)
#Заменить максимальный элемент на ноль 
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)
#Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
Z = np.zeros((10,10), [("x",float),("y",float)])
Z["x"], Z["y"] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)
#Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))
#Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)
#Найти ближайшее к заданному значению число в заданном массиве
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])
#Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
Z = np.zeros(10, [ ("position", [ ("x", float, 1),
("y", float, 1)]),
("color", [ ("r", float, 1),
("g", float, 1),
("b", float, 1)])])

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:133: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
