<a href="https://colab.research.google.com/github/AlinaSharonova/AlinaSharonova/blob/master/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Библиотека Numpy**

In [1]:
import numpy as np
a = np.array([0, 2, 1])
print(a, type(a))
b = np.array([1, 4, 5, 8],
float)
print(b, type(b))

[0 2 1] <class 'numpy.ndarray'>
[1. 4. 5. 8.] <class 'numpy.ndarray'>


In [4]:
import numpy as np
b = np.array([1, 4, 5, 8],
float)
print(b, type(b))
print(b[:2])
print(b[2:])
print(b[3])
b[0]=20
print(b)

[1. 4. 5. 8.] <class 'numpy.ndarray'>
[1. 4.]
[5. 8.]
8.0
[20.  4.  5.  8.]


In [14]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
print(a)
print(a[0,0])
print(a[0,1])
print(a[1,0])
print ("------------------------------------")
print(a[1,:])
print(a[:,2])
print(a[-1:, -2:])
print("Shape a - ", a.shape)
print("Type a - ", a.dtype)
print(len(a))
print(len(a[0]))
print(len(a[1]))
print(2 in a)
print(0 in a)

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0
4.0
------------------------------------
[4. 5. 6.]
[3. 6.]
[[5. 6.]]
Shape a -  (2, 3)
Type a -  float64
2
3
3
True
False


In [16]:
import numpy as np
a = np.array([1,2], float)
b = np.array([3,4,5,6],
float)
c = np.array([7,8,9], float)
print("A:", a)
print("B:", b)
print("C:", c)
print("Concatenate:")
d=np.concatenate((a, b, c))
print(d)

A: [1. 2.]
B: [3. 4. 5. 6.]
C: [7. 8. 9.]
Concatenate:
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [17]:
import numpy as np
a = np.array([[1, 2], [3, 4]],
float)
b = np.array([[5, 6], [7,8]], float)
print("A:")
print(a)
print("B:")
print(b)
print("Concatenate:")
c=np.concatenate((a,b))
print(c)
print("Concatenate axis=0:")
d=np.concatenate((a,b), axis=0)
print(d)
print("Concatenate axis=1:")
e=np.concatenate((a,b), axis=1)
print(e)

A:
[[1. 2.]
 [3. 4.]]
B:
[[5. 6.]
 [7. 8.]]
Concatenate:
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenate axis=0:
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenate axis=1:
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [30]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
b=np.zeros_like(a)
c= np.ones_like(a)
print("A:")
print(a)
print("B:")
print(b)
print("C:")
print(c)

A:
[[1. 2. 3.]
 [4. 5. 6.]]
B:
[[0. 0. 0.]
 [0. 0. 0.]]
C:
[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
import numpy as np
a=np.identity(4,
dtype=float)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
import numpy as np
a=np.eye(4, k=1,
dtype=float)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


цикл с параметром 11 и 21


11. Дано целое число N (> 0). Найти сумму

N^2 + (N + 1)^2 + (N + 2)^2 + . . . + (2·N)^2

(целое число).

In [21]:
N=2
sum = 0
sum += N**2
k=N
while k != 0:
  sum+= (N+k)**2
  k = k - 1
print(sum)

29


21. Дано целое число N (> 0). Используя один цикл, найти сумму

1 + 1/(1!) + 1/(2!) + 1/(3!) + . . . + 1/(N!)

(выражение N! — N–факториал — обозначает произведение всех целых

чисел от 1 до N: N! = 1·2·. . .·N). Полученное число является прибли-
женным значением константы e = exp(1).

In [36]:
N=2
s= 0
s= s+1
f= 1
i = 1
while i<=N:
  f= f*i
  s= s+ 1/f
  i += 1
print (s)

2.5
